### ISSUE TITLE
嗨，你好，请问如何把这个组件嵌入到react native项目中

### ISSUE THREAD

**Issue by gitcyrabbit** [droidwolf/react-native-RealRecyclerView#2]

**Comment by droidwolf** [comment]
1,copy My*.java &RealRecycler*.java file to your project.
2,setup UIImplementationProvider 
  ReactInstanceManager.Builder.setUIImplementationProvider(new MyUIImplementationProvider())
[《react native Android 真正回收复用 RecyclerView/ListView》](https://my.oschina.net/droidwolf/blog/750479)

**Comment by codetomylaw** [comment]
@droidwolf  这个组件实际的使用场景是什么？

**Comment by droidwolf** [comment]
见[README](https://github.com/droidwolf/react-native-RealRecyclerView/blob/master/README.md)
