### ISSUE TITLE
 hi,如何改造下才能增加下拉刷新上拉加载？THX

### ISSUE THREAD

**Issue by gitcyrabbit** [droidwolf/react-native-RealRecyclerView#3]

**Comment by droidwolf** [comment]
下拉刷新用。这个demo场景不解决这种需求
[react-native-refreshable-listview](http://www.oschina.net/p/react-native-refreshable-listview)

**Comment by codetomylaw** [comment]
react-native-refreshable-listview 好像也没有解决ListView的内存问题啊？
