### ISSUE TITLE
Add ios support

### ISSUE THREAD

**Issue by sibelius** [droidwolf/react-native-RealRecyclerView#7]
Tks for the great work!

I think it is worth to bring the ios implementation for this repo, and create a npm package for this component, that could be easily replace ListView current implementation

**Comment by droidwolf** [comment]
I'm not IOS development.
If you have a solution for IOS, welcomed the pull request.
ios you can use[list-view-experiments](https://github.com/wix/list-view-experiments).
[Facebook does not advocate using the recyclerview](https://github.com/facebook/react-native/pull/11445).

**Comment by sibelius** [comment]
we can also compare:

- WindowedListView - https://github.com/facebook/react-native/blob/master/Libraries/Experimental/WindowedListView.js
- FlatList - https://github.com/facebook/react-native/blob/master/Libraries/Experimental/FlatList.js

**Comment by droidwolf** [comment]
good,

**Comment by asciiman** [comment]
With permission from @talkol and @droidwolf I have combined the two libraries into a single npm package that works on both iOS and Android.

https://github.com/asciiman/react-native-native-listview

Enjoy!

**Comment by droidwolf** [comment]
Great.Thanks for your work.@asciiman
