### ISSUE TITLE
界面较复杂时会出问题

### ISSUE THREAD

**Issue by reallin** [droidwolf/react-native-RealRecyclerView#9]
当界面复杂点就复用就会出问题，如界面渲染一个标题和一张图片如下时，下滑后再上滑就会有空白出现。请问怎么解决呢。
`import React, { Component } from 'react';
import { 
  AppRegistry,
  StyleSheet,
  Text,
  View,
    Image,
  Dimensions
} from 'react-native';

import RealRecyclerView from './realRecyclerView.android.js';
const sightIcon = require('./image/ic_scenery.jpg');
const ROWS_IN_DATA_SOURCE = 600;
const dataSource = [];
for (let i=0; i<ROWS_IN_DATA_SOURCE; i++) dataSource.push(`hi droidwolf。 row=${i}。hahha`);

class HelloWorld extends Component {
  render() {
    return (
        <RealRecyclerView
		style={styles.container}
          renderRow={this.renderRow}
          numRows={dataSource.length}
          rowHeight={200}
        />
    );
  }
  
  renderRow(rowID) {
    return (

        <View  style = {styles.container}>
             <Text  style={styles.welcome}>
                 {dataSource[rowID]}
             </Text>
             <Image
             style={styles.icon}
             source={sightIcon}
             />
             </View>
    );
  }

}

const styles = StyleSheet.create({

    container: {
        flexDirection:'column',
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#F5FCFF',
    },

    icon:{
        width: Dimensions.get('window').width,
        height:150
    },

    welcome: {
        fontSize: 20,
        textAlign: 'center',
        margin: 10,
    },
});`

**Comment by droidwolf** [comment]
1,icon style填充了宽度
`icon:{
    width: Dimensions.get('window').width,
    height:150
},`
2，android的recyclerView复用试图导致图片加载问题，需要自己管理图片
